# theme = "modus_vivendi_tritanopia"
# theme = "carbonfox"
theme = "github_dark_high_contrast"
# theme = "modus_vivendi"
# theme = "naysayer"
# theme = "gruvbox_dark_hard"
# theme = "emacs"
# theme = "gruber-darker"
# theme = "darcula"

[editor]
mouse = true
# lsp.enable = false
auto-completion = true
auto-format = false
rulers = [100]
idle-timeout = 800


[editor.smart-tab]
enable = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = { j = "normal_mode" }
"C-c" = "normal_mode"

[keys.normal]
"g" = { "S" = ["vsplit", "jump_view_up", "goto_definition"] }
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
"space" = { "f" = ":format" }
# "C-p" = "file_picker"
"C-p" = "file_picker_in_current_directory"
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"C-k" = "jump_view_up"
"C-j" = "jump_view_down"
"H" = "move_prev_sub_word_start"
"L" = "move_next_sub_word_end"

[editor.lsp]
display-inlay-hints = true
